version: '3'
services:
   back:
     build:
       context: .
       dockerfile: Dockerfile
     command: gunicorn --workers=2 --threads=2 api_test.wsgi -b 0.0.0.0:8000 --log-file=-
     container_name: pokeapiBackEnd
     volumes:
       - .:/code
     ports:
       - "8000:8000"
